postgres:
  image: dr2.rbkmoney.com/rbkmoney/postgres-geodata:0eb52256576ec22f89fadc3e7fe505b692e838a3
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_DB: columbus
  entrypoint:
   - /docker-entrypoint.sh
   - postgres
  ports:
    - '5432:5432'
  volumes:
    - ~/.docker-volumes/rbkmoney/columbus/postgresql/data:/var/lib/postgresql/data